version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ checksum "package.json" }}
      - run: yarn run lint
      # - run: yarn test
  deploy:
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "package.json" }}
      - run: yarn install
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run:
          name: nuxt generate
          command: |
            DEPLOY_ENV=GH_PAGES CTF_BLOG_POST_TYPE_ID=$CTF_BLOG_POST_TYPE_ID CTF_CDA_ACCESS_TOKEN=$CTF_CDA_ACCESS_TOKEN CTF_PREVIEW_ACCESS_TOKEN=$CTF_PREVIEW_ACCESS_TOKEN CTF_SPACE_ID=$CTF_SPACE_ID nuxt-ts generate
      - run: yarn run deploy:gh-pages
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master