version: 2.1

parameters:
  article_update:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ checksum "package.json" }}
      - run: yarn run lint
      - deploy:
          name: contents_update
          command: |
            if [[ true ]]; then
              curl --user ${CIRCLE_API_USER_TOKEN}: \
              --data build_parameters[CIRCLE_JOB]=deploy \
              --data revision=$CIRCLE_SHA1 \
              https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            fi

  deploy:
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "package.json" }}
      - run: yarn install
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run: yarn run generate:gh-pages
      - run: yarn run deploy:gh-pages
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master